service: aws-python-flask-api

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app
  customDomain:
    domainName: sls.tappy.com.ph
    basePath: ${opt:stage, 'dev'}
    stage: $default
    createRoute53Record: false
    certificateArn: 'arn:aws:acm:us-east-1:672256646492:certificate/44e7bc1a-690a-455a-a742-c33fe03dac09'
    endpointType: regional
    apiType: http

provider:
  name: aws
  runtime: python3.9

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi:
          path: '*'
          method: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-domain-manager