name: Deploy Serverless
on:
  push:
    branches: [ "master" ]
    paths:
      - 'serverless/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      - name: Change to serverless directory
        run: cd serverless
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Install Serverless Framework
        run: npm i -g serverless
      - name: Install plugins
        run: |
          serverless plugin install -n serverless-wsgi
          serverless plugin install -n serverless-python-requirements
          serverless plugin install -n serverless-domain-manager
      - name: Install serverless wsgi
        run: serverless plugin install -n serverless-wsgi
      - name: serverless package
        run: serverless package
      - name: Deploy to Lambda
        run: serverless deploy